services:
  - type: web
    name: kulturamind-api
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PYTHONUNBUFFERED
        value: "true"

